apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-templates
  description: The Make Monmouth Backstage Templates
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: matt@doics.co
  lifecycle: production
